# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KWFrXKztSsTaJ-cIPaWUeaRprYWNm0ay
"""

import pandas as pd
import sqlite3 as sql
conn = sql.connect('/content/download.db')
query = '''
SELECT
    checkouts.checkout_id, checkouts.member_id, checkouts.book_id, checkouts.checkout_date, checkouts.return_date,
    members.first_name, members.last_name, members.grade, members.neighborhood, members.membership_status, members.join_date
FROM checkouts
JOIN members ON checkouts.member_id = members.member_id;
'''
df1 = pd.read_sql_query(query, conn)
df2 = pd.read_json('/content/download.json')
df3 = pd.read_html('/content/download.html')[0]
df_combined = pd.concat

all_checkouts = pd.concat([df1, df3], ignore_index= True)
final_df = pd.merge(all_checkouts, df2, on = 'book_id', how = 'left')
final_df.to_csv('task1_combined_data.csv', index = False)